---
# Source: kafka/templates/burrow-config.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: burrow-default-config
data:
  burrow.toml: |-
    [zookeeper]
    servers=["zookeeper-default.component:2181"]
    timeout=6
    root-path="/burrow"

    [client-profile.client]
    client-id="burrow-client"
    kafka-version="0.10.0"
    sasl="saslprofile"

    [sasl.saslprofile]
    username="KAFKA_USERNAME"
    password="KAFKA_PASSWORD"
    handshake-first=true

    [cluster.kafka-default]
    class-name="kafka"
    servers=[ "kafka-default:9092"]
    topic-refresh=60
    offset-refresh=30
    client-profile="client"

    [consumer.kafka-default]
    class-name="kafka"
    cluster="kafka-default"
    servers=["kafka-default:9092"]
    group-blacklist=""
    group-whitelist=""
    client-profile="client"

    [consumer.kafka-default-zk]
    class-name="kafka_zk"
    cluster="kafka-default"
    servers=["zookeeper-default.component:2181"]
    zookeeper-path="/tracking_kafka"
    zookeeper-timeout=30
    group-blacklist=""
    group-whitelist=""
    [httpserver.default]
    address=":8000"