---
# Source: kafka/templates/burrow-service.yaml
kind: Service
apiVersion: v1
metadata:
  name: burrow-default
  labels:
    app.kubernetes.io/version: "2.12-2.2.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: burrow-default
spec:
  selector:
    app.kubernetes.io/instance: burrow-default
  ports:
  - name: api
    port: 8000
  - name: prometheus
    port: 8080
