apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: redis-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redis-role-binding
roleRef:
  kind: Role
  name: redis-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: redis-sa
  namespace: default