---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-default
  labels:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/instance: zookeeper-default
    app.kubernetes.io/version: "1.0-3.4.13"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/instance: zookeeper-default
spec:
  clusterIP: None
  ports:
    - port: 2181
      name: client
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
    - port: 7071
      name: http-metrics
  selector:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/instance: zookeeper-default
