---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper-default
  labels:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/instance: zookeeper-default
    app.kubernetes.io/version: "1.0-3.4.13"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 3
  serviceName: zookeeper-default
  selector:
    matchLabels:
      app.kubernetes.io/name: zookeeper
      app.kubernetes.io/instance: zookeeper-default
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zookeeper
        app.kubernetes.io/instance: zookeeper-default
    spec:
      nodeSelector:
        viper.sensetime.com/node-components: "True"
      
      imagePullSecrets:
        - name: inner
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      containers:
        - name: zookeeper
          image: "{ip}:5000/infra/zookeeper-1.0-3.4.13:914008e-amd64"
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              cpu: "4"
              memory: 4Gi
            requests:
              cpu: "2"
              memory: 4Gi
          ports:
            - name: client
              containerPort: 2181
            - name: server
              containerPort: 2888
            - name: leader-election
              containerPort: 3888
            - name: http-metrics
              containerPort: 7071
          env:
            - name : ZK_ENSEMBLE
              value: "zookeeper-default-0zookeeper-default-1zookeeper-default-2"
            - name : ZK_REPLICAS
              value: "3"
            - name : ZK_HEAP_SIZE
              valueFrom:
                configMapKeyRef:
                    name: zookeeper-default-config
                    key: jvm.heap
            - name : ZK_TICK_TIME
              valueFrom:
                configMapKeyRef:
                    name: zookeeper-default-config
                    key: tick
            - name : ZK_INIT_LIMIT
              valueFrom:
                configMapKeyRef:
                    name: zookeeper-default-config
                    key: init
            - name : ZK_SYNC_LIMIT
              valueFrom:
                configMapKeyRef:
                    name: zookeeper-default-config
                    key: tick
            - name : ZK_MAX_CLIENT_CNXNS
              valueFrom:
                configMapKeyRef:
                    name: zookeeper-default-config
                    key: client.cnxns
            - name: ZK_SNAP_RETAIN_COUNT
              valueFrom:
                configMapKeyRef:
                    name: zookeeper-default-config
                    key: snap.retain
            - name: ZK_PURGE_INTERVAL
              valueFrom:
                configMapKeyRef:
                    name: zookeeper-default-config
                    key: purge.interval
            - name: ZK_CLIENT_PORT
              value: "2181"
            - name: ZK_SERVER_PORT
              value: "2888"
            - name: ZK_ELECTION_PORT
              value: "3888"
          command:
            - sh
            - -c
            - "start-zookeeper \
              --servers=3 \
              --data_dir=/var/lib/zookeeper/data \
              --data_log_dir=/var/lib/zookeeper/data/log \
              --conf_dir=/opt/zookeeper/conf \
              --client_port=2181 \
              --election_port=3888 \
              --server_port=2888 \
              --tick_time=2000 \
              --init_limit=10 \
              --sync_limit=5 \
              --heap=${ZK_HEAP_SIZE} \
              --max_client_cnxns=9000 \
              --snap_retain_count=3 \
              --purge_interval=12 \
              --max_session_timeout=40000 \
              --min_session_timeout=4000 \
              --log_level=INFO"
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - "/zookeeper-ready 2181"
            initialDelaySeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - "/zookeeper-ready 2181"
            initialDelaySeconds: 30
            timeoutSeconds: 5
          volumeMounts:
          - name: localvolume
            mountPath: /var/lib/zookeeper
  volumeClaimTemplates:
  - metadata:
      name: localvolume
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: storageclass-local-zookeeper
      resources:
        requests:
          storage: 4G
