---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zookeeper-default-servicemonitor
  namespace: monitoring
  labels:
    k8s-app: zookeeper-default
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      app.kubernetes.io/name: zookeeper
      app.kubernetes.io/instance: zookeeper-default
  namespaceSelector:
    matchNames:
    - component
  endpoints:
  - port: http-metrics
    interval: 30s
    honorLabels: true
