version: '3'    
services:    
  jenkins:    
    image: jenkins:lts    
    environment:    
      JENKINS_SYNC_MODE: master-slave    
      JENKINS_SYNC_HTTP_PORT: 8080    
      HTTPS_KEYSTORE_PATH: /path/to/keystore    
      HTTPS_KEYSTORE_PASSWORD: password    
      HTTPS_CERTIFICATE_FILE: /path/to/cert.pem    
      HTTPS_CERTIFICATE_PASSWORD: password    
    ports:    
      - "8080:8080"    
    volumes:    
      - /var/jenkins_home/:/var/jenkins_home/    
    jenkins_home:    
      image: jenkins/jenkins:lts    
    environment:    
      JENKINS_SYNC_MODE: master-slave    
      JENKINS_SYNC_HTTP_PORT: 8080    
    ports:    
      - "8080:8080"    
    volumes:    
      - /var/jenkins_home/:/var/jenkins_home/    
    slave:    
      image: jenkins/jenkins:lts    
      environment:    
        JENKINS_SYNC_MODE: master-slave    
        JENKINS_SYNC_HTTP_PORT: 8080    
        HTTPS_KEYSTORE_PATH: /path/to/keystore    
        HTTPS_KEYSTORE_PASSWORD: password    
        HTTPS_CERTIFICATE_FILE: /path/to/cert.pem    
        HTTPS_CERTIFICATE_PASSWORD: password    
    ports:    
      - "8080:8080"    
    volumes:    
      - /var/jenkins_home/:/var/jenkins_home/    
    slave_home:    
      image: jenkins/jenkins:lts    
    environment:    
      JENKINS_SYNC_MODE: master-slave    
      JENKINS_SYNC_HTTP_PORT: 8080    
    ports:    
      - "8080:8080"    
    volumes:    
      - /var/jenkins_home/:/var/jenkins_home/    
  slave_label:    
    image: jenkins/jenkins:lts    
    environment:    
      JENKINS_SYNC_MODE: master-slave    
      JENKINS_SYNC_HTTP_PORT: 8080    
    ports:    
      - "8080:8080"    
    volumes:    
      - /var/jenkins_home/:/var/jenkins_home/    
    slave_home:    
      image: jenkins/jenkins:lts    
    environment:    
      JENKINS_SYNC_MODE: master-slave    
      JENKINS_SYNC_HTTP_PORT: 8080    
    ports:    
      - "8080:8080"    
    volumes:    
      - /var/jenkins_home/:/var/jenkins_home/    